name: Build Cordova Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Java & Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android App
        run: |
          cordova platform add android
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: daytracker-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: daytracker-aab
          path: platforms/android/app/build/outputs/bundle/release/*.aab
